# Generated by Django 4.2.1 on 2023-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_session_year_staff_subject_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/subject_pdfs'),
        ),
    ]
