# Generated by Django 4.2.1 on 2023-06-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_participant_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_leave',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant'),
        ),
    ]
